/rest/user/:
  get:
    queryParameters:
      firstName:
        type: string
      lastName:
        type: string
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "id": "http://scraml.io/user.json",
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "age": {
                    "type": "integer"
                  },
                  "homePage": {
                    "$ref": "http://scraml.io/link.json"
                  }
                }
              }
  post:
    body:
      multipart/form-data:
    responses:
      200:
        body:

